### PR TITLE
fix: Use `std::nothrow` to disable exceptions throwing in `new` operators (fixes #103).

### LINKED ISSUE #103: Misuse of checking nullptr returned from `new`.
### Bug

The current code base checks nullptrs returned from `new` to detect out-of-memory issues. This is wrong because by default, OOM will throw a std exception. We can disable this by passing `std::nothrow` to the `new` operator.

### clp-ffi-py version

b0df0dc78b2110d59f2fe6d87d1298c444cbf914

### Environment

Any

### Reproduction steps

Nothing to reproduce

### PR DESCRIPTION
**Pull request by LinZhihao-723**
# Description

This PR fixes #103.
For all `new` operators, we now use `std::nothrow` to explicitly disable exception throwing. As a result, we need to check manually whether the returned pointer is null and set out-of-memory errors accordingly.

# Validation performed

- Ensure workflows passed.

## Summary by CodeRabbit

- **New Features**
	- Enhanced memory management and error handling across various components, ensuring improved stability during memory allocation.
  
- **Bug Fixes**
	- Implemented robust error handling for memory allocation failures, preventing potential crashes and ensuring appropriate error messages are raised.

- **Documentation**
	- Updated comments and documentation strings for clarity regarding method parameters and expected behaviors.

### CODE REVIEW

File: src/clp_ffi_py/ir/native/PyDeserializer.cpp [hunk 1]
```diff
@@ -279,7 +289,12 @@ auto PyDeserializer::handle_log_event(clp::ffi::KeyValuePairLogEvent&& log_event
         // deserialized log event.
         clear_deserialized_log_event();
     }
-    m_deserialized_log_event = new clp::ffi::KeyValuePairLogEvent{std::move(log_event)};
+    m_deserialized_log_event
+            = new (std::nothrow) clp::ffi::KeyValuePairLogEvent{std::move(log_event)};
+    if (nullptr == m_deserialized_log_event) {
+        // TODO: Set this to a proper error code when user-defined error code is supported.
+        return IRErrorCode::IRErrorCode_Eof;
```
Comment (haiqi96) [inline src/clp_ffi_py/ir/native/PyDeserializer.cpp:296]: maybe we should return IRErrorCode::NoMem. 
Unfortuately it will require updating clp repo so obviously out of scope of this PR, lol

**Review by haiqi96 — APPROVED** [review]
The change looks reasonable.

Title is also good.

File: src/clp_ffi_py/ir/native/PyDeserializer.cpp (hunk 1 above)
Comment (LinZhihao-723) [reply src/clp_ffi_py/ir/native/PyDeserializer.cpp:296]: Sigh, correct. I'm trying to proceed error handling improvements. Hopefully we will have the user-defined user code supported soon.
